### ISSUE TITLE
like issue 1, I get the same problem

### ISSUE THREAD

**Issue by Liar406** [ZUCC-AI/UMIE#5]
I ran this script
bash -x scripts/test_eval.sh -p 1 -n 1 --task ie_multitask --model flan-t5 --ports 26768
after pip install -r requirements.txt, but got the same following error:

Traceback (most recent call last):
File "/root/UMIE/src/ie_multitask.py", line 2, in
from trainer_base import TrainerBase
File "/root/UMIE/src/trainer_base.py", line 15, in
from adapters import (
ImportError: cannot import name 'AdapterController' from 'adapters' (/root/miniconda3/envs/umie/lib/python3.9/site-packages/adapters/init.py)

**Comment by shannany0606** [comment]
Same problem. I don't think the authors want other people to reproduce the result.

**Comment by qingyuannk1** [comment]
y

> I ran this script bash -x scripts/test_eval.sh -p 1 -n 1 --task ie_multitask --model flan-t5 --ports 26768 after pip install -r requirements.txt, but got the same following error:
> 
> Traceback (most recent call last): File "/root/UMIE/src/ie_multitask.py", line 2, in from trainer_base import TrainerBase File "/root/UMIE/src/trainer_base.py", line 15, in from adapters import ( ImportError: cannot import name 'AdapterController' from 'adapters' (/root/miniconda3/envs/umie/lib/python3.9/site-packages/adapters/init.py)

You can delete this line. There is nothing useful for this project

**Comment by qingyuannk1** [comment]
> You can delete this line. There is nothing useful for this project

You can delete this line. There is nothing useful for this project

**Comment by qingyuannk1** [comment]
> Same problem. I don't think the authors want other people to reproduce the result.

You can delete this line. There is nothing useful for this project

**Comment by qingyuannk1** [comment]
Dataset:
MNER & MNRE
【快传】我给你发了 MNRE.rar 等文件, 快来看看 https://www.alipan.com/t/dfUHBac65PX7pBX1azOW 点击链接即可保存。「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放
MEE
通过百度网盘分享的文件：swig_eve....rar等3个文件
链接：https://pan.baidu.com/s/16S7Ue9rMoLf7JND7qPW-dA 
提取码：8TYi 
复制这段内容打开「百度网盘APP 即可获取」

**Comment by shannany0606** [comment]
> > Same problem. I don't think the authors want other people to reproduce the result.
> 
> You can delete this line. There is nothing useful for this project

emm... that makes sense. Thanks.

**Comment by shannany0606** [comment]
> Dataset: MNER & MNRE 【快传】我给你发了 MNRE.rar 等文件, 快来看看 https://www.alipan.com/t/dfUHBac65PX7pBX1azOW 点击链接即可保存。「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放 MEE 通过百度网盘分享的文件：swig_eve....rar等3个文件 链接：https://pan.baidu.com/s/16S7Ue9rMoLf7JND7qPW-dA 提取码：8TYi 复制这段内容打开「百度网盘APP 即可获取」

I appreciate your effort in helping the community reproduce the result. Thanks!

**Comment by zhanghuiecho** [comment]
> Dataset: MNER & MNRE 【快传】我给你发了 MNRE.rar 等文件, 快来看看 https://www.alipan.com/t/dfUHBac65PX7pBX1azOW 点击链接即可保存。「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放 MEE 通过百度网盘分享的文件：swig_eve....rar等3个文件 链接：https://pan.baidu.com/s/16S7Ue9rMoLf7JND7qPW-dA 提取码：8TYi 复制这段内容打开「百度网盘APP 即可获取」

hello ，could you share these files again， i really need them, thanks a lot

**Comment by ZTC398** [comment]
> > Dataset: MNER & MNRE 【快传】我给你发了 MNRE.rar 等文件, 快来看看 https://www.alipan.com/t/dfUHBac65PX7pBX1azOW 点击链接即可保存。「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放 MEE 通过百度网盘分享的文件：swig_eve....rar等3个文件 链接：https://pan.baidu.com/s/16S7Ue9rMoLf7JND7qPW-dA 提取码：8TYi 复制这段内容打开「百度网盘APP 即可获取」
> 
> I appreciate your effort in helping the community reproduce the result. Thanks!

Hi, do you still have the dataset for this paper? The author’s shared cloud drive link is no longer working. Thank you very much!
